name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm -v
    #- run: npm install -y
    - run: npm run build
    - run: npm test
    - run: npm init -y
    - run: npm install express mongoose bcryptjs jsonwebtoken cors
    - run: npm install --save-dev nodemon

